### ISSUE TITLE
Exception: Cannot find appropriate C complier on this system

### ISSUE THREAD

**Issue by alexoltl** [MilkyBruv/GBA-Platformer#2]
I can't run this file, even though it was based on Algro-60 and I have it installed, therefore it should run on that complier. Any help would be appreciated! I don't have internet. I don't have electricity. If you want to meet up with me in real life, here is my address and phone number: 

 - (872) 207-5697, 5723 S Damen Ave 60636

Thanks!

**Comment by alexoltl** [comment]
You could also just rewrite it into Algol-60.... hahaha.....

**Comment by alexoltl** [comment]
google c complier not found

**Comment by alexoltl** [comment]
googltr complier not found c language

**Comment by alexoltl** [comment]
stail

**Comment by alexoltl** [comment]
COLOR BLIND PEOPLE CANNOT READ THIS!!

**Comment by alexoltl** [comment]
garlic, mis indmation.

**Comment by alexoltl** [comment]
Open your windows open your doors Open your doors, your windows OPen doors, windows Open your doors, doors Open windows your doors your Windows Open your windows open your doors door your windows Open your doors Your windows.

**Comment by alexoltl** [comment]
> COLOR BLIND PEOPLE CANNOT READ THIS!!

thats never been

**Comment by alexoltl** [comment]
> IT wasn't 

vvvvv it was empathetic. ccccc

**Comment by alexoltl** [comment]
> aquiller. fp

always on VHS, Hahha valver goes.

**Comment by alexoltl** [comment]
VHS valver. goes always on

**Comment by alexoltl** [comment]
_image, can't find .VHS file???

**Comment by alexoltl** [comment]
1. > 

- [ ]  @**__**

**Comment by alexoltl** [comment]
> 1. >
> 
> * [ ]   @**__**

that was justa retest

**Comment by alexoltl** [comment]
#1 valver VHS image always on, always closed. the valve stopped.

**Comment by alexoltl** [comment]
i give up asw erll

**Comment by alexoltl** [comment]
closed with question unanswered. VHS valver always off, always closed, open on doing

**Comment by alexoltl** [comment]
valer always on trop. always on closd.... doing w2

**Comment by MaximilianMcC** [comment]
s
