### ISSUE TITLE
mark down tutoral

### ISSUE THREAD

**Issue by MaximilianMcC** [MilkyBruv/GBA-Platformer#4]
ok this is how u us mark down (mark bro 90) #3 im make it

for a heading u make a # hash tag there can be 6 in totla it slegit h1-h6 so like#test is h1 and ######is h6 <h6> equivelent
# h1
### h3
```md
# h1
## h2
### h3
```

o ya text is just text its like p !!
```md
o ya text is just text its like p !!
```

for a list its a - dashh charater makes a list no number
- play csgo
- run school
- cj
```md
- play csgo
- run school
- cj
```

ummmm if you want to do a list number with number you wriee 1. like 1 then a dot (.)
1. play csgo
1. run school
1. cj
its same as 
```md
1.  play csgo
1. run school
1. cj
```

um fancy text its like a **bald** and *italic* is main ok use a 8 character asterick * shift 8
**shift 8**
*shift 8*
```md
**shift 8**
*shift 8*
```

link like i show your my favourite iwkieda page for a https://en.wikipedia.org/wiki/Markdown im [alt text](im link)
[wiki pedia ](https://en.wikipedia.org/wiki/Markdown)
```md
[wiki pedia ](https://en.wikipedia.org/wiki/Markdown)
```
do U see how the tet in alt text [][][][] is a for the titlr.... wow

image same but a !!!!! shfit 1
![capcha](https://i.imgur.com/UIL69kp.png)
wow ok this how i do it the captuca if its like not load
```md
![capcha](https://i.imgur.com/UIL69kp.png)
```
wow

code bloc k like for sharing th code that thngy next to 1 above tab idk``
um its 2 of them for a `in line like this` or you can do a for a like
```py
print("im")
```
languag 3 of it 
```md
um its 2 of them for a `in line like this` or you can do a for a like
```py
print("im")
``'
languag 3 of it 
```

o yea U can also write normal htmel in it 

ok by😃

**Comment by alexoltl** [comment]
👨‍👨‍👦

**Comment by alexoltl** [comment]
i left the kitchen too many times 🥱🥱🥱🥱
